# 03 Попытка в рельное решение

Задача предсказать куда пойдет пара на следующий день

In [2]:
import importlib
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

import models, timeseries_cv
importlib.reload(models); importlib.reload(timeseries_cv)
from models import (GRUWithAttention, WindowDataset, SoftDirectionalHuberLoss,
                    CURATED_FEATURES, z_feature_cols, get_device)
from timeseries_cv import (cross_validate, summarize_cv, compare_strategies,
                           evaluate_holdout)
from models import save_checkpoint, load_checkpoint
from pathlib import Path

SEED = 42
np.random.seed(SEED); torch.manual_seed(SEED)
DEVICE = get_device()
CKPT_PATH = Path('checkpoints/gru_attention_btc_eth.pt')
print('device:', DEVICE)

device: mps

## Загрузка данных, ограничение до BTC + ETH

Объединяем train+val в пул для CV; test полностью откладываем для финальной
holdout-оценки.

In [3]:
HEADLINE = ['BTC-USD', 'ETH-USD']

def load(split):
    return pd.read_csv(f'data/{split}_features.csv', index_col=0, parse_dates=True)

train_df = load('train'); val_df = load('val'); test_df = load('test')

def restrict(df, coins):
    return df[df['ticker'].isin(coins)].sort_index()

cv_df_h   = restrict(pd.concat([train_df, val_df]), HEADLINE)
test_df_h = restrict(test_df, HEADLINE)

print('CV pool :', len(cv_df_h), 'rows |', cv_df_h.index.min().date(), '->', cv_df_h.index.max().date())
print('Holdout :', len(test_df_h), 'rows |', sorted(test_df_h["ticker"].unique()))

CV pool : 4368 rows | 2019-07-18 -> 2025-07-09
Holdout : 488 rows | ['BTC-USD', 'ETH-USD']

In [4]:
# Feature set: the curated core-8 (high-signal, low-variance choice).
feature_cols = list(CURATED_FEATURES)
# Sanity: all present in the data.
missing = [c for c in feature_cols if c not in cv_df_h.columns]
assert not missing, f'missing features: {missing}'
print(f'features ({len(feature_cols)}):', feature_cols)
print(f'(full z_* set available: {len(z_feature_cols(cv_df_h))} cols — swap in for an ablation)')

features (8): ['bull_regime', 'z_bb_pct_b', 'z_volume_z20', 'z_log_close_return_1', 'z_range', 'z_ret_autocorr', 'dow_cos', 'high_vol_regime']
(full z_* set available: 43 cols — swap in for an ablation)

## Time-series кросс-валидация: expanding vs sliding

Обе стратегии нарезают фолды по **дате через все тикеры**; затем `WindowDataset`
строит последовательности внутри каждого тикера. Явно передаём
`SoftDirectionalHuberLoss` (стандарт проекта) и используем расписание
warmup→cosine.

In [5]:
SEQ_LEN = 20
criterion = SoftDirectionalHuberLoss(delta=1.01, dir_weight=0.8, sharpness=10.0)

# Single source of truth for the architecture — also saved into the checkpoint.
ARCH_CONFIG = dict(input_size=len(feature_cols), hidden_size=32,
                   num_layers=3, linear_hidden=32, dropout=0.1)

def model_factory(seed=SEED):
    torch.manual_seed(seed)
    return GRUWithAttention(**ARCH_CONFIG).to(DEVICE)

shared = dict(
    full_df=cv_df_h, feature_cols=feature_cols,
    model_factory=model_factory, dataset_cls=WindowDataset,
    n_folds=5, val_frac=0.10, seq_len=SEQ_LEN, batch_size=128,
    lr=1e-3, epochs=1000, patience=13, huber_delta=1.01,
    device=DEVICE, criterion=criterion, weight_decay=1e-1, warmup_epochs=10,
)

In [6]:
exp_results = cross_validate(**shared, strategy='expanding')
exp_df = summarize_cv(exp_results)
exp_df

============================================================
  [EXPANDING] Fold 0  |  train 2019-07-18 → 2021-12-06  |  val 2021-12-07 → 2022-07-12
============================================================
  Epoch   1  train_loss=0.7406  val_loss=0.7332  dir_acc=0.533
  Epoch   2  train_loss=0.5748  val_loss=0.4567  dir_acc=0.533
  Epoch   3  train_loss=0.3954  val_loss=0.4817  dir_acc=0.472
  Epoch   4  train_loss=0.3793  val_loss=0.4215  dir_acc=0.545
  Epoch   5  train_loss=0.3769  val_loss=0.4052  dir_acc=0.535
  Epoch   6  train_loss=0.3902  val_loss=0.3931  dir_acc=0.528
  Epoch   7  train_loss=0.3659  val_loss=0.4451  dir_acc=0.462
  Epoch   8  train_loss=0.3947  val_loss=0.4215  dir_acc=0.530
  Epoch   9  train_loss=0.3892  val_loss=0.4354  dir_acc=0.492
  Epoch  10  train_loss=0.3606  val_loss=0.3978  dir_acc=0.548
  Epoch  11  train_loss=0.4104  val_loss=0.4282  dir_acc=0.505
  Epoch  12  train_loss=0.3760  val_loss=0.4044  dir_acc=0.530
  Epoch  13  train_loss=0.3727  val_loss=0.3848  dir_acc=0.545
  Epoch  14  train_loss=0.3642  val_loss=0.4091  dir_acc=0.535
  Epoch  15  train_loss=0.3748  val_loss=0.4438  dir_acc=0.472
  Epoch  16  train_loss=0.3758  val_loss=0.3840  dir_acc=0.551
  Epoch  17  train_loss=0.3579  val_loss=0.3799  dir_acc=0.573
  Epoch  18  train_loss=0.3471  val_loss=0.3763  dir_acc=0.556
  Epoch  19  train_loss=0.3721  val_loss=0.3707  dir_acc=0.553
  Epoch  20  train_loss=0.3715  val_loss=0.3768  dir_acc=0.563
  Epoch  21  train_loss=0.3485  val_loss=0.3519  dir_acc=0.563
  Epoch  22  train_loss=0.3599  val_loss=0.3937  dir_acc=0.553
  Epoch  23  train_loss=0.3597  val_loss=0.3660  dir_acc=0.566
  Epoch  24  train_loss=0.3420  val_loss=0.3689  dir_acc=0.545
  Epoch  25  train_loss=0.3492  val_loss=0.3581  dir_acc=0.561
  Epoch  26  train_loss=0.3409  val_loss=0.3677  dir_acc=0.561
  Epoch  27  train_loss=0.3269  val_loss=0.3426  dir_acc=0.568
  Epoch  28  train_loss=0.3380  val_loss=0.3389  dir_acc=0.563
  Epoch  29  train_loss=0.3310  val_loss=0.3249  dir_acc=0.578
  Epoch  30  train_loss=0.3213  val_loss=0.3185  dir_acc=0.568
  Epoch  31  train_loss=0.3109  val_loss=0.3159  dir_acc=0.588
  Epoch  32  train_loss=0.3246  val_loss=0.3140  dir_acc=0.571
  Epoch  33  train_loss=0.3162  val_loss=0.3188  dir_acc=0.581
  Epoch  34  train_loss=0.3117  val_loss=0.3233  dir_acc=0.568
  Epoch  35  train_loss=0.2974  val_loss=0.3356  dir_acc=0.581
  Epoch  36  train_loss=0.2991  val_loss=0.3453  dir_acc=0.561
  Epoch  37  train_loss=0.2987  val_loss=0.3382  dir_acc=0.576
  Epoch  38  train_loss=0.2908  val_loss=0.3275  dir_acc=0.568
  Epoch  39  train_loss=0.3001  val_loss=0.3233  dir_acc=0.583
  Epoch  40  train_loss=0.2887  val_loss=0.3525  dir_acc=0.566
  Epoch  41  train_loss=0.2956  val_loss=0.3587  dir_acc=0.573
  Epoch  42  train_loss=0.2969  val_loss=0.3162  dir_acc=0.591
  Epoch  43  train_loss=0.3176  val_loss=0.3389  dir_acc=0.588
  Epoch  44  train_loss=0.3100  val_loss=0.3508  dir_acc=0.548
  Epoch  45  train_loss=0.2836  val_loss=0.3413  dir_acc=0.586
  Early stop at epoch 45.

============================================================
  [EXPANDING] Fold 1  |  train 2019-07-18 → 2022-09-05  |  val 2022-09-06 → 2023-04-11
============================================================
  Epoch   1  train_loss=0.7342  val_loss=0.7069  dir_acc=0.490
  Epoch   2  train_loss=0.5171  val_loss=0.3394  dir_acc=0.485
  Epoch   3  train_loss=0.4192  val_loss=0.2863  dir_acc=0.508
  Epoch   4  train_loss=0.4103  val_loss=0.3607  dir_acc=0.490
  Epoch   5  train_loss=0.3813  val_loss=0.2643  dir_acc=0.543
  Epoch   6  train_loss=0.3614  val_loss=0.2966  dir_acc=0.528
  Epoch   7  train_loss=0.3775  val_loss=0.3377  dir_acc=0.490
  Epoch   8  train_loss=0.3478  val_loss=0.2705  dir_acc=0.551
  Epoch   9  train_loss=0.3597  val_loss=0.3149  dir_acc=0.503
  Epoch  10  train_loss=0.3524  val_loss=0.3208  dir_acc=0.520
  Epoch  11  train_loss=0.3869  val_loss=0.2868  dir_acc=0.528
  Epoch  12  train_loss=0.3918  val_loss=0.2884  dir_acc=0.545
  Epoch  13  train_loss=0.3862  val_loss=0.3279  dir_acc=0.490
  Epoch  14  train_loss=0.3680  val_loss=0.3373  dir_acc=0.505
  Epoch  15  train_loss=0.3576  val_loss=0.3157  dir_acc=0.513
  Epoch  16  train_loss=0.3567  val_loss=0.3250  dir_acc=0.500
  Epoch  17  train_loss=0.3536  val_loss=0.2872  dir_acc=0.533
  Epoch  18  train_loss=0.3531  val_loss=0.3042  dir_acc=0.523
  Early stop at epoch 18.

============================================================
  [EXPANDING] Fold 2  |  train 2019-07-18 → 2023-06-05  |  val 2023-06-06 → 2024-01-09
============================================================
  Epoch   1  train_loss=0.7329  val_loss=0.7254  dir_acc=0.482
  Epoch   2  train_loss=0.4999  val_loss=0.3637  dir_acc=0.520
  Epoch   3  train_loss=0.3864  val_loss=0.3419  dir_acc=0.548
  Epoch   4  train_loss=0.3845  val_loss=0.3558  dir_acc=0.523
  Epoch   5  train_loss=0.3493  val_loss=0.3487  dir_acc=0.528
  Epoch   6  train_loss=0.3844  val_loss=0.4125  dir_acc=0.518
  Epoch   7  train_loss=0.3750  val_loss=0.3448  dir_acc=0.533
  Epoch   8  train_loss=0.3409  val_loss=0.3717  dir_acc=0.515
  Epoch   9  train_loss=0.3688  val_loss=0.3690  dir_acc=0.508
  Epoch  10  train_loss=0.3475  val_loss=0.3768  dir_acc=0.520
  Epoch  11  train_loss=0.3554  val_loss=0.3472  dir_acc=0.523
  Epoch  12  train_loss=0.3583  val_loss=0.3459  dir_acc=0.508
  Epoch  13  train_loss=0.3444  val_loss=0.3697  dir_acc=0.525
  Epoch  14  train_loss=0.3394  val_loss=0.3864  dir_acc=0.533
  Epoch  15  train_loss=0.3567  val_loss=0.3714  dir_acc=0.520
  Epoch  16  train_loss=0.3283  val_loss=0.3562  dir_acc=0.515
  Early stop at epoch 16.

============================================================
  [EXPANDING] Fold 3  |  train 2019-07-18 → 2024-03-04  |  val 2024-03-05 → 2024-10-08
============================================================
  Epoch   1  train_loss=0.7276  val_loss=0.7332  dir_acc=0.482
  Epoch   2  train_loss=0.4898  val_loss=0.3640  dir_acc=0.480
  Epoch   3  train_loss=0.3880  val_loss=0.3735  dir_acc=0.503
  Epoch   4  train_loss=0.3761  val_loss=0.3107  dir_acc=0.533
  Epoch   5  train_loss=0.3728  val_loss=0.2929  dir_acc=0.543
  Epoch   6  train_loss=0.3521  val_loss=0.3059  dir_acc=0.528
  Epoch   7  train_loss=0.3502  val_loss=0.3209  dir_acc=0.538
  Epoch   8  train_loss=0.3568  val_loss=0.3917  dir_acc=0.495
  Epoch   9  train_loss=0.3713  val_loss=0.3704  dir_acc=0.495
  Epoch  10  train_loss=0.3488  val_loss=0.3103  dir_acc=0.528
  Epoch  11  train_loss=0.3461  val_loss=0.3228  dir_acc=0.535
  Epoch  12  train_loss=0.3297  val_loss=0.3004  dir_acc=0.543
  Epoch  13  train_loss=0.3436  val_loss=0.3626  dir_acc=0.495
  Epoch  14  train_loss=0.3591  val_loss=0.3450  dir_acc=0.505
  Epoch  15  train_loss=0.3448  val_loss=0.3596  dir_acc=0.490
  Epoch  16  train_loss=0.3402  val_loss=0.3015  dir_acc=0.533
  Epoch  17  train_loss=0.3288  val_loss=0.3005  dir_acc=0.553
  Epoch  18  train_loss=0.3296  val_loss=0.3811  dir_acc=0.487
  Early stop at epoch 18.

============================================================
  [EXPANDING] Fold 4  |  train 2019-07-18 → 2024-12-03  |  val 2024-12-04 → 2025-07-09
============================================================
  Epoch   1  train_loss=0.7264  val_loss=0.6712  dir_acc=0.497
  Epoch   2  train_loss=0.4451  val_loss=0.3442  dir_acc=0.508
  Epoch   3  train_loss=0.3732  val_loss=0.3316  dir_acc=0.515
  Epoch   4  train_loss=0.3661  val_loss=0.3220  dir_acc=0.545
  Epoch   5  train_loss=0.3728  val_loss=0.2797  dir_acc=0.558
  Epoch   6  train_loss=0.3886  val_loss=0.3118  dir_acc=0.525
  Epoch   7  train_loss=0.3645  val_loss=0.3193  dir_acc=0.533
  Epoch   8  train_loss=0.3438  val_loss=0.2800  dir_acc=0.571
  Epoch   9  train_loss=0.3543  val_loss=0.2934  dir_acc=0.568
  Epoch  10  train_loss=0.3490  val_loss=0.3157  dir_acc=0.548
  Epoch  11  train_loss=0.3423  val_loss=0.3285  dir_acc=0.545
  Epoch  12  train_loss=0.3469  val_loss=0.3282  dir_acc=0.520
  Epoch  13  train_loss=0.3418  val_loss=0.3236  dir_acc=0.528
  Epoch  14  train_loss=0.3299  val_loss=0.2985  dir_acc=0.556
  Epoch  15  train_loss=0.3380  val_loss=0.3255  dir_acc=0.515
  Epoch  16  train_loss=0.3465  val_loss=0.3607  dir_acc=0.503
  Epoch  17  train_loss=0.3279  val_loss=0.3400  dir_acc=0.513
  Epoch  18  train_loss=0.3272  val_loss=0.3548  dir_acc=0.520
  Early stop at epoch 18.

============================================================
  EXPANDING-WINDOW CV SUMMARY
============================================================
  Fold 0  |  val_loss=0.3140  dir_acc=0.571  |  train=1,706  val=396
  Fold 1  |  val_loss=0.2643  dir_acc=0.543  |  train=2,252  val=396
  Fold 2  |  val_loss=0.3419  dir_acc=0.548  |  train=2,798  val=396
  Fold 3  |  val_loss=0.2929  dir_acc=0.543  |  train=3,344  val=396
  Fold 4  |  val_loss=0.2797  dir_acc=0.558  |  train=3,892  val=396

  val_loss  : 0.2986 ± 0.0303
  dir_acc   : 0.553 ± 0.012
============================================================

,fold_idx,strategy,train_loss,val_loss,val_mae,val_dir_acc,n_train,n_val,train_start,train_end,val_start,val_end,best_model_state,val_index
0,0,expanding,0.324581,0.313989,0.777524,0.570707,1706,396,2019-07-18,2021-12-06,2021-12-07,2022-07-12,"{'gru.weight_ih_l0': [[tensor(0.1418, device='...","DatetimeIndex(['2021-12-27', '2021-12-28', '20..."
1,1,expanding,0.381268,0.264292,0.626312,0.542929,2252,396,2019-07-18,2022-09-05,2022-09-06,2023-04-11,"{'gru.weight_ih_l0': [[tensor(0.1421, device='...","DatetimeIndex(['2022-09-26', '2022-09-27', '20..."
2,2,expanding,0.386413,0.341897,0.698884,0.547980,2798,396,2019-07-18,2023-06-05,2023-06-06,2024-01-09,"{'gru.weight_ih_l0': [[tensor(0.1390, device='...","DatetimeIndex(['2023-06-26', '2023-06-27', '20..."
3,3,expanding,0.372766,0.292900,0.685969,0.542929,3344,396,2019-07-18,2024-03-04,2024-03-05,2024-10-08,"{'gru.weight_ih_l0': [[tensor(0.1445, device='...","DatetimeIndex(['2024-03-25', '2024-03-26', '20..."
4,4,expanding,0.372768,0.279728,0.679316,0.558081,3892,396,2019-07-18,2024-12-03,2024-12-04,2025-07-09,"{'gru.weight_ih_l0': [[tensor(0.1439, device='...","DatetimeIndex(['2024-12-24', '2024-12-25', '20..."

In [7]:
sli_results = cross_validate(**shared, strategy='sliding')
sli_df = summarize_cv(sli_results)
sli_df

============================================================
  [SLIDING] Fold 0  |  train 2019-07-18 → 2021-12-06  |  val 2021-12-07 → 2022-07-12
============================================================
  Epoch   1  train_loss=0.7406  val_loss=0.7332  dir_acc=0.533
  Epoch   2  train_loss=0.5748  val_loss=0.4567  dir_acc=0.533
  Epoch   3  train_loss=0.3954  val_loss=0.4817  dir_acc=0.472
  Epoch   4  train_loss=0.3793  val_loss=0.4215  dir_acc=0.545
  Epoch   5  train_loss=0.3769  val_loss=0.4052  dir_acc=0.535
  Epoch   6  train_loss=0.3902  val_loss=0.3931  dir_acc=0.528
  Epoch   7  train_loss=0.3659  val_loss=0.4451  dir_acc=0.462
  Epoch   8  train_loss=0.3947  val_loss=0.4215  dir_acc=0.530
  Epoch   9  train_loss=0.3892  val_loss=0.4354  dir_acc=0.492
  Epoch  10  train_loss=0.3606  val_loss=0.3978  dir_acc=0.548
  Epoch  11  train_loss=0.4104  val_loss=0.4282  dir_acc=0.505
  Epoch  12  train_loss=0.3760  val_loss=0.4044  dir_acc=0.530
  Epoch  13  train_loss=0.3727  val_loss=0.3848  dir_acc=0.545
  Epoch  14  train_loss=0.3642  val_loss=0.4091  dir_acc=0.535
  Epoch  15  train_loss=0.3748  val_loss=0.4438  dir_acc=0.472
  Epoch  16  train_loss=0.3758  val_loss=0.3840  dir_acc=0.551
  Epoch  17  train_loss=0.3579  val_loss=0.3799  dir_acc=0.573
  Epoch  18  train_loss=0.3471  val_loss=0.3763  dir_acc=0.556
  Epoch  19  train_loss=0.3721  val_loss=0.3707  dir_acc=0.553
  Epoch  20  train_loss=0.3715  val_loss=0.3768  dir_acc=0.563
  Epoch  21  train_loss=0.3485  val_loss=0.3519  dir_acc=0.563
  Epoch  22  train_loss=0.3599  val_loss=0.3937  dir_acc=0.553
  Epoch  23  train_loss=0.3597  val_loss=0.3660  dir_acc=0.566
  Epoch  24  train_loss=0.3420  val_loss=0.3689  dir_acc=0.545
  Epoch  25  train_loss=0.3492  val_loss=0.3581  dir_acc=0.561
  Epoch  26  train_loss=0.3409  val_loss=0.3677  dir_acc=0.561
  Epoch  27  train_loss=0.3269  val_loss=0.3426  dir_acc=0.568
  Epoch  28  train_loss=0.3380  val_loss=0.3389  dir_acc=0.563
  Epoch  29  train_loss=0.3310  val_loss=0.3249  dir_acc=0.578
  Epoch  30  train_loss=0.3213  val_loss=0.3185  dir_acc=0.568
  Epoch  31  train_loss=0.3109  val_loss=0.3159  dir_acc=0.588
  Epoch  32  train_loss=0.3246  val_loss=0.3140  dir_acc=0.571
  Epoch  33  train_loss=0.3162  val_loss=0.3188  dir_acc=0.581
  Epoch  34  train_loss=0.3117  val_loss=0.3233  dir_acc=0.568
  Epoch  35  train_loss=0.2974  val_loss=0.3356  dir_acc=0.581
  Epoch  36  train_loss=0.2991  val_loss=0.3453  dir_acc=0.561
  Epoch  37  train_loss=0.2987  val_loss=0.3382  dir_acc=0.576
  Epoch  38  train_loss=0.2908  val_loss=0.3275  dir_acc=0.568
  Epoch  39  train_loss=0.3001  val_loss=0.3233  dir_acc=0.583
  Epoch  40  train_loss=0.2887  val_loss=0.3525  dir_acc=0.566
  Epoch  41  train_loss=0.2956  val_loss=0.3587  dir_acc=0.573
  Epoch  42  train_loss=0.2969  val_loss=0.3162  dir_acc=0.591
  Epoch  43  train_loss=0.3176  val_loss=0.3389  dir_acc=0.588
  Epoch  44  train_loss=0.3100  val_loss=0.3508  dir_acc=0.548
  Epoch  45  train_loss=0.2836  val_loss=0.3413  dir_acc=0.586
  Early stop at epoch 45.

============================================================
  [SLIDING] Fold 1  |  train 2020-04-16 → 2022-09-05  |  val 2022-09-06 → 2023-04-11
============================================================
  Epoch   1  train_loss=0.7324  val_loss=0.7178  dir_acc=0.490
  Epoch   2  train_loss=0.5701  val_loss=0.3970  dir_acc=0.490
  Epoch   3  train_loss=0.4107  val_loss=0.3173  dir_acc=0.505
  Epoch   4  train_loss=0.3932  val_loss=0.2837  dir_acc=0.538
  Epoch   5  train_loss=0.3932  val_loss=0.3405  dir_acc=0.490
  Epoch   6  train_loss=0.3519  val_loss=0.2836  dir_acc=0.535
  Epoch   7  train_loss=0.3611  val_loss=0.2812  dir_acc=0.563
  Epoch   8  train_loss=0.3812  val_loss=0.2582  dir_acc=0.556
  Epoch   9  train_loss=0.3846  val_loss=0.3356  dir_acc=0.492
  Epoch  10  train_loss=0.3863  val_loss=0.2704  dir_acc=0.566
  Epoch  11  train_loss=0.3794  val_loss=0.2782  dir_acc=0.561
  Epoch  12  train_loss=0.3692  val_loss=0.3331  dir_acc=0.492
  Epoch  13  train_loss=0.4018  val_loss=0.2932  dir_acc=0.528
  Epoch  14  train_loss=0.3596  val_loss=0.2716  dir_acc=0.576
  Epoch  15  train_loss=0.3706  val_loss=0.2755  dir_acc=0.535
  Epoch  16  train_loss=0.3581  val_loss=0.2772  dir_acc=0.533
  Epoch  17  train_loss=0.3633  val_loss=0.2407  dir_acc=0.583
  Epoch  18  train_loss=0.3396  val_loss=0.3105  dir_acc=0.513
  Epoch  19  train_loss=0.3743  val_loss=0.3043  dir_acc=0.510
  Epoch  20  train_loss=0.3205  val_loss=0.3222  dir_acc=0.505
  Epoch  21  train_loss=0.3677  val_loss=0.2740  dir_acc=0.518
  Epoch  22  train_loss=0.3659  val_loss=0.2651  dir_acc=0.548
  Epoch  23  train_loss=0.3276  val_loss=0.2732  dir_acc=0.540
  Epoch  24  train_loss=0.3277  val_loss=0.2895  dir_acc=0.540
  Epoch  25  train_loss=0.3145  val_loss=0.2935  dir_acc=0.535
  Epoch  26  train_loss=0.3221  val_loss=0.3035  dir_acc=0.543
  Epoch  27  train_loss=0.3054  val_loss=0.3134  dir_acc=0.503
  Epoch  28  train_loss=0.3175  val_loss=0.3128  dir_acc=0.535
  Epoch  29  train_loss=0.3065  val_loss=0.3021  dir_acc=0.510
  Epoch  30  train_loss=0.3243  val_loss=0.2925  dir_acc=0.540
  Early stop at epoch 30.

============================================================
  [SLIDING] Fold 2  |  train 2021-01-14 → 2023-06-05  |  val 2023-06-06 → 2024-01-09
============================================================
  Epoch   1  train_loss=0.7631  val_loss=0.7461  dir_acc=0.482
  Epoch   2  train_loss=0.5939  val_loss=0.4560  dir_acc=0.482
  Epoch   3  train_loss=0.3775  val_loss=0.4215  dir_acc=0.518
  Epoch   4  train_loss=0.4066  val_loss=0.3821  dir_acc=0.523
  Epoch   5  train_loss=0.3382  val_loss=0.3404  dir_acc=0.551
  Epoch   6  train_loss=0.3290  val_loss=0.3490  dir_acc=0.538
  Epoch   7  train_loss=0.3159  val_loss=0.3716  dir_acc=0.515
  Epoch   8  train_loss=0.3246  val_loss=0.3809  dir_acc=0.528
  Epoch   9  train_loss=0.3188  val_loss=0.3851  dir_acc=0.518
  Epoch  10  train_loss=0.3295  val_loss=0.3830  dir_acc=0.510
  Epoch  11  train_loss=0.3042  val_loss=0.3835  dir_acc=0.520
  Epoch  12  train_loss=0.3125  val_loss=0.3818  dir_acc=0.505
  Epoch  13  train_loss=0.3036  val_loss=0.3949  dir_acc=0.520
  Epoch  14  train_loss=0.3216  val_loss=0.3639  dir_acc=0.530
  Epoch  15  train_loss=0.3073  val_loss=0.3619  dir_acc=0.530
  Epoch  16  train_loss=0.2949  val_loss=0.3622  dir_acc=0.523
  Epoch  17  train_loss=0.3414  val_loss=0.3823  dir_acc=0.513
  Epoch  18  train_loss=0.3212  val_loss=0.3652  dir_acc=0.515
  Early stop at epoch 18.

============================================================
  [SLIDING] Fold 3  |  train 2021-10-14 → 2024-03-04  |  val 2024-03-05 → 2024-10-08
============================================================
  Epoch   1  train_loss=0.7510  val_loss=0.7680  dir_acc=0.482
  Epoch   2  train_loss=0.5895  val_loss=0.4535  dir_acc=0.482
  Epoch   3  train_loss=0.3815  val_loss=0.3299  dir_acc=0.520
  Epoch   4  train_loss=0.3629  val_loss=0.3367  dir_acc=0.497
  Epoch   5  train_loss=0.3868  val_loss=0.3659  dir_acc=0.482
  Epoch   6  train_loss=0.3482  val_loss=0.3396  dir_acc=0.492
  Epoch   7  train_loss=0.3464  val_loss=0.3703  dir_acc=0.503
  Epoch   8  train_loss=0.3818  val_loss=0.3082  dir_acc=0.525
  Epoch   9  train_loss=0.3061  val_loss=0.3014  dir_acc=0.530
  Epoch  10  train_loss=0.3305  val_loss=0.2910  dir_acc=0.548
  Epoch  11  train_loss=0.3476  val_loss=0.2870  dir_acc=0.538
  Epoch  12  train_loss=0.3143  val_loss=0.3132  dir_acc=0.530
  Epoch  13  train_loss=0.3195  val_loss=0.3274  dir_acc=0.505
  Epoch  14  train_loss=0.3181  val_loss=0.3384  dir_acc=0.510
  Epoch  15  train_loss=0.3554  val_loss=0.3482  dir_acc=0.505
  Epoch  16  train_loss=0.3639  val_loss=0.3413  dir_acc=0.510
  Epoch  17  train_loss=0.3304  val_loss=0.3104  dir_acc=0.520
  Epoch  18  train_loss=0.3446  val_loss=0.3167  dir_acc=0.528
  Epoch  19  train_loss=0.3202  val_loss=0.2915  dir_acc=0.543
  Epoch  20  train_loss=0.3104  val_loss=0.2987  dir_acc=0.548
  Epoch  21  train_loss=0.2964  val_loss=0.2934  dir_acc=0.548
  Epoch  22  train_loss=0.3000  val_loss=0.3172  dir_acc=0.543
  Epoch  23  train_loss=0.3008  val_loss=0.3096  dir_acc=0.533
  Epoch  24  train_loss=0.3019  val_loss=0.3107  dir_acc=0.543
  Early stop at epoch 24.

============================================================
  [SLIDING] Fold 4  |  train 2022-07-15 → 2024-12-03  |  val 2024-12-04 → 2025-07-09
============================================================
  Epoch   1  train_loss=0.7590  val_loss=0.7149  dir_acc=0.497
  Epoch   2  train_loss=0.5898  val_loss=0.4152  dir_acc=0.497
  Epoch   3  train_loss=0.3795  val_loss=0.3615  dir_acc=0.520
  Epoch   4  train_loss=0.3612  val_loss=0.3616  dir_acc=0.518
  Epoch   5  train_loss=0.3747  val_loss=0.3614  dir_acc=0.508
  Epoch   6  train_loss=0.3340  val_loss=0.3573  dir_acc=0.503
  Epoch   7  train_loss=0.3655  val_loss=0.3677  dir_acc=0.510
  Epoch   8  train_loss=0.3249  val_loss=0.3513  dir_acc=0.520
  Epoch   9  train_loss=0.3298  val_loss=0.3350  dir_acc=0.528
  Epoch  10  train_loss=0.3394  val_loss=0.3009  dir_acc=0.571
  Epoch  11  train_loss=0.3210  val_loss=0.3296  dir_acc=0.538
  Epoch  12  train_loss=0.3044  val_loss=0.3290  dir_acc=0.543
  Epoch  13  train_loss=0.3332  val_loss=0.3234  dir_acc=0.568
  Epoch  14  train_loss=0.3162  val_loss=0.3483  dir_acc=0.528
  Epoch  15  train_loss=0.3384  val_loss=0.3609  dir_acc=0.505
  Epoch  16  train_loss=0.2936  val_loss=0.3423  dir_acc=0.523
  Epoch  17  train_loss=0.3103  val_loss=0.3431  dir_acc=0.530
  Epoch  18  train_loss=0.2940  val_loss=0.3534  dir_acc=0.528
  Epoch  19  train_loss=0.2941  val_loss=0.3508  dir_acc=0.515
  Epoch  20  train_loss=0.2926  val_loss=0.3558  dir_acc=0.520
  Epoch  21  train_loss=0.3094  val_loss=0.3718  dir_acc=0.508
  Epoch  22  train_loss=0.3193  val_loss=0.4218  dir_acc=0.437
  Epoch  23  train_loss=0.2945  val_loss=0.3999  dir_acc=0.492
  Early stop at epoch 23.

============================================================
  SLIDING-WINDOW CV SUMMARY
============================================================
  Fold 0  |  val_loss=0.3140  dir_acc=0.571  |  train=1,706  val=396
  Fold 1  |  val_loss=0.2407  dir_acc=0.583  |  train=1,706  val=396
  Fold 2  |  val_loss=0.3404  dir_acc=0.551  |  train=1,706  val=396
  Fold 3  |  val_loss=0.2870  dir_acc=0.538  |  train=1,706  val=396
  Fold 4  |  val_loss=0.3009  dir_acc=0.571  |  train=1,706  val=396

  val_loss  : 0.2966 ± 0.0369
  dir_acc   : 0.563 ± 0.018
============================================================

,fold_idx,strategy,train_loss,val_loss,val_mae,val_dir_acc,n_train,n_val,train_start,train_end,val_start,val_end,best_model_state,val_index
0,0,sliding,0.324581,0.313989,0.777524,0.570707,1706,396,2019-07-18,2021-12-06,2021-12-07,2022-07-12,"{'gru.weight_ih_l0': [[tensor(0.1418, device='...","DatetimeIndex(['2021-12-27', '2021-12-28', '20..."
1,1,sliding,0.363287,0.240671,0.618123,0.583333,1706,396,2020-04-16,2022-09-05,2022-09-06,2023-04-11,"{'gru.weight_ih_l0': [[tensor(0.1395, device='...","DatetimeIndex(['2022-09-26', '2022-09-27', '20..."
2,2,sliding,0.338172,0.340384,0.700144,0.550505,1706,396,2021-01-14,2023-06-05,2023-06-06,2024-01-09,"{'gru.weight_ih_l0': [[tensor(0.1402, device='...","DatetimeIndex(['2023-06-26', '2023-06-27', '20..."
3,3,sliding,0.347631,0.286969,0.686049,0.537879,1706,396,2021-10-14,2024-03-04,2024-03-05,2024-10-08,"{'gru.weight_ih_l0': [[tensor(0.1510, device='...","DatetimeIndex(['2024-03-25', '2024-03-26', '20..."
4,4,sliding,0.339416,0.300933,0.679056,0.570707,1706,396,2022-07-15,2024-12-03,2024-12-04,2025-07-09,"{'gru.weight_ih_l0': [[tensor(0.1490, device='...","DatetimeIndex(['2024-12-24', '2024-12-25', '20..."

In [8]:
comp_df = compare_strategies(exp_results, sli_results)
comp_df

============================================================
  STRATEGY COMPARISON
============================================================
  expanding   |  dir_acc = 0.553 ± 0.011  |  val_loss = 0.2986 ± 0.0271
  sliding     |  dir_acc = 0.563 ± 0.016  |  val_loss = 0.2966 ± 0.0330

  → Sliding wins: older data may be hurting. Consider shorter history.
  → Expanding is more stable across folds (lower variance).
============================================================

,strategy,val_loss_mean,val_loss_std,dir_acc_mean,dir_acc_std,n_folds,best_fold_acc,worst_fold_acc
0,expanding,0.298561,0.027119,0.552525,0.010642,5,0.570707,0.542929
1,sliding,0.296589,0.033042,0.562626,0.016240,5,0.583333,0.537879

## Holdout-оценка (test) против бейзлайнов, по тикерам + агрегат

In [9]:
holdout = evaluate_holdout(
    train_df=cv_df_h, eval_df=test_df_h,
    feature_cols=feature_cols, model_factory=model_factory,
    dataset_cls=WindowDataset, lr=1e-3, device=DEVICE,
    seq_len=SEQ_LEN, batch_size=128, epochs=1000, patience=13,
    huber_delta=1.01, criterion=criterion, weight_decay=1e-1, warmup_epochs=10,
    ticker=HEADLINE,
)
print(f'Aggregate holdout directional accuracy: {holdout.eval_dir_acc:.4f}')
print(f'Holdout loss: {holdout.eval_loss:.4f}')
print('\nPer-ticker:')
for tk, m in holdout.per_ticker.items():
    print(f'  {tk:8s}: dir_acc {m["dir_acc"]:.4f}')

============================================================
  HOLDOUT EVALUATION  |  ticker=BTC-USD, ETH-USD
  train 2019-07-18 -> 2025-07-09  (4,368 rows)
  eval  2025-07-10 -> 2026-03-10  (488 rows)
============================================================
  Epoch   1  train_loss=0.7297  eval_loss=0.7687  dir_acc=0.475
  Epoch   2  train_loss=0.4429  eval_loss=0.4483  dir_acc=0.513
  Epoch   3  train_loss=0.3554  eval_loss=0.4105  dir_acc=0.540
  Epoch   4  train_loss=0.3705  eval_loss=0.3984  dir_acc=0.551
  Epoch   5  train_loss=0.3746  eval_loss=0.4101  dir_acc=0.554
  Epoch   6  train_loss=0.3465  eval_loss=0.4280  dir_acc=0.536
  Epoch   7  train_loss=0.3720  eval_loss=0.3787  dir_acc=0.558
  Epoch   8  train_loss=0.3483  eval_loss=0.3860  dir_acc=0.556
  Epoch   9  train_loss=0.3554  eval_loss=0.4004  dir_acc=0.558
  Epoch  10  train_loss=0.3573  eval_loss=0.4360  dir_acc=0.536
  Epoch  11  train_loss=0.3604  eval_loss=0.4210  dir_acc=0.547
  Epoch  12  train_loss=0.3373  eval_loss=0.4185  dir_acc=0.542
  Epoch  13  train_loss=0.3308  eval_loss=0.3950  dir_acc=0.545
  Epoch  14  train_loss=0.3367  eval_loss=0.3874  dir_acc=0.569
  Epoch  15  train_loss=0.3317  eval_loss=0.4321  dir_acc=0.542
  Epoch  16  train_loss=0.3350  eval_loss=0.3897  dir_acc=0.558
  Epoch  17  train_loss=0.3287  eval_loss=0.4231  dir_acc=0.522
  Epoch  18  train_loss=0.3205  eval_loss=0.4452  dir_acc=0.518
  Epoch  19  train_loss=0.3270  eval_loss=0.4145  dir_acc=0.540
  Epoch  20  train_loss=0.3158  eval_loss=0.4519  dir_acc=0.513
  Early stop at epoch 20.

============================================================
  HOLDOUT RESULT  |  ticker=BTC-USD, ETH-USD
============================================================
  eval_loss : 0.3787
  eval_mae  : 0.8039
  dir_acc   : 0.558
  n_train   : 4,328
  n_eval    : 448
  best epoch: 7

  ticker            loss   dir_acc       n
  BTC-USD         0.4417     0.540     224
  ETH-USD         0.3158     0.576     224

  dummy_loss: 0.4517  (predict zero)
  delta loss: -0.0729  (better than dummy)
  delta dir : +0.058
============================================================
Aggregate holdout directional accuracy: 0.5580
Holdout loss: 0.3787

Per-ticker:
  BTC-USD : dir_acc 0.5402
  ETH-USD : dir_acc 0.5759

## Экспорт чекпойнта

In [10]:
save_checkpoint(
    holdout.model, CKPT_PATH,
    config=ARCH_CONFIG, feature_cols=feature_cols, seq_len=SEQ_LEN,
    arch='GRUWithAttention',
    metrics={'holdout_dir_acc': float(holdout.eval_dir_acc),
             'holdout_loss': float(holdout.eval_loss),
             'tickers': HEADLINE},
)
print('saved checkpoint ->', CKPT_PATH)

# Sanity: reload and confirm holdout dir-acc is reproduced from the saved weights.
reloaded, payload = load_checkpoint(CKPT_PATH, device=DEVICE)
print('reloaded arch:', payload['arch'], '| features:', len(payload['feature_cols']),
      '| saved metrics:', payload['metrics'])

saved checkpoint -> checkpoints/gru_attention_btc_eth.pt
reloaded arch: GRUWithAttention | features: 8 | saved metrics: {'holdout_dir_acc': 0.5580357313156128, 'holdout_loss': 0.3787465989589691, 'tickers': ['BTC-USD', 'ETH-USD']}

In [11]:
# Naive baselines on the same holdout for context.
from models import directional_accuracy
y = test_df_h['target'].values
maj = np.sign(np.nanmean(y))  # always-up / always-down
print(f'Majority-sign baseline : {directional_accuracy(np.full_like(y, maj), y):.4f}')
print(f'Always-up baseline     : {directional_accuracy(np.ones_like(y), y):.4f}')
print(f'PCA+Logistic baseline  : 0.5593  (from experiments/pca_svm_baseline.ipynb)')
print(f'GRU+Attention (ours)   : {holdout.eval_dir_acc:.4f}')

Majority-sign baseline : 0.5287
Always-up baseline     : 0.4713
PCA+Logistic baseline  : 0.5593  (from experiments/pca_svm_baseline.ipynb)
GRU+Attention (ours)   : 0.5580

## Сравнение архитектур

GRU+Attention — основная (прогнана вживую выше). Остальные строки — **значения
последнего прогона** holdout из ноутбуков-источников в `experiments/`
(перезапустите, чтобы обновить). Они используют общие `models.py` /
`timeseries_cv.py`, поэтому сравнение «яблоки к яблокам».

In [12]:
comparison = pd.DataFrame([
    {'model': 'GRU + Attenti (headline, live)', 'cv_dir_acc_expanding': 0.552,
     'holdout_dir_acc': round(float(holdout.eval_dir_acc), 4), 'source': 'this notebook'},
    {'model': 'GRU + Attention (advanced)', 'cv_dir_acc_expanding': 0.541,
     'holdout_dir_acc': 0.534, 'source': 'experiments/gru_attention_advanced.ipynb'},
    {'model': 'GRU + Attention (iter2)', 'cv_dir_acc_expanding': 0.549,
     'holdout_dir_acc': 0.509, 'source': 'experiments/gru_attention_iter2.ipynb'},
    {'model': 'Two-head GRU (dir + magnitude)', 'cv_dir_acc_expanding': None,
     'holdout_dir_acc': 0.543, 'source': 'experiments/two_head_gru_attention.ipynb'},
    {'model': 'Dir + Vol combined (dir-only)', 'cv_dir_acc_expanding': None,
     'holdout_dir_acc': 0.568, 'source': 'experiments/dir_vol_combined.ipynb'},
    {'model': 'PCA + Logistic (classical baseline)', 'cv_dir_acc_expanding': None,
     'holdout_dir_acc': 0.541, 'source': 'experiments/pca_svm_baseline.ipynb'},
])
comparison

,model,cv_dir_acc_expanding,holdout_dir_acc,source
0,"GRU + Attenti (headline, live)",0.552,0.558,this notebook
1,GRU + Attention (advanced),0.541,0.534,experiments/gru_attention_advanced.ipynb
2,GRU + Attention (iter2),0.549,0.509,experiments/gru_attention_iter2.ipynb
3,Two-head GRU (dir + magnitude),NaN,0.543,experiments/two_head_gru_attention.ipynb
4,Dir + Vol combined (dir-only),NaN,0.568,experiments/dir_vol_combined.ipynb
5,PCA + Logistic (classical baseline),NaN,0.541,experiments/pca_svm_baseline.ipynb

## Выводы

- С новой задачей модель справляется лучше
- Скользящее окно примерно одниково по метрикам с расширающимся (variance на расширщемся ниже)
- 55-56% - Это потолок для OCHLV метрик (судя по схожим моделям)